services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: agendaplus
      POSTGRES_PASSWORD: agendaplus
      POSTGRES_DB: agendaplus
    ports:
      - "5432:5432"
    volumes:
      - agendaplus_pgdata:/var/lib/postgresql/data

volumes:
  agendaplus_pgdata:
